[project]
name = "tts-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch",
    "scikit-learn",
    "librosa>=0.11.0",
    "pandas>=2.3.3",
    "torchaudio>=2.9.1",
    "matplotlib>=3.10.7",
]
